In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('archive/pokemon.csv')
df.head()

         Name  Type1   Type2   Evolution
0   bulbasaur  Grass  Poison     ivysaur
1     ivysaur  Grass  Poison    venusaur
2    venusaur  Grass  Poison         NaN
3  charmander   Fire     NaN  charmeleon
4  charmeleon   Fire     NaN   charizard

In [4]:
df_temp = df.drop('Evolution', axis=1)

df_temp = df_temp.sort_values('Name')

df_copy = df_temp.reset_index(drop=True)
df_copy.head()

              Name    Type1  Type2
0        abomasnow    Grass    Ice
1             abra  Psychic    NaN
2            absol     Dark    NaN
3         accelgor      Bug    NaN
4  aegislash-blade    Steel  Ghost

In [6]:
df_copy['image'] = 'archive/images/' + df_copy['Name'].str.lower().str.replace(' ', '-') + '.png'
df_copy.head()

              Name    Type1  Type2                               image
0        abomasnow    Grass    Ice        archive/images/abomasnow.png
1             abra  Psychic    NaN             archive/images/abra.png
2            absol     Dark    NaN            archive/images/absol.png
3         accelgor      Bug    NaN         archive/images/accelgor.png
4  aegislash-blade    Steel  Ghost  archive/images/aegislash-blade.png